# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iosAppSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosAppSwift
  pod 'shared', :path => '../shared'
  pod 'webrtc-kmp', :git => 'git@github.com:shepeliev/webrtc-kmp.git'

end
